# Basic Operations with Matrices

In [1]:

import numpy as np

A = np.array([[1, 2, -10, 4], [3, 4, 5, -6], [3, 3, -2, 5]])
B = np.array([3, 3, 4, 2])

print("A:", A)
print("B:", B)

A: [[  1   2 -10   4]
 [  3   4   5  -6]
 [  3   3  -2   5]]
B: [3 3 4 2]


### Function to determine the length of the largest dimension

In [2]:
def length(matrix):
    return max(matrix.shape)

lent =A.shape
print(lent)

lengthA = length(A)
lengthB = length(B)
print("lengthA:", lengthA)
print("lengthB:", lengthB)

(3, 4)
lengthA: 4
lengthB: 4


### A neat trick to stack Matrices

In [3]:
C= np.vstack((A, B))
arr= np.array([[1],[2],[3],[4]])
result= np.hstack((C, arr))
result

array([[  1,   2, -10,   4,   1],
       [  3,   4,   5,  -6,   2],
       [  3,   3,  -2,   5,   3],
       [  3,   3,   4,   2,   4]])

### Building from other matrices

In [4]:
D = C[1:4, 2:4]
print("D:", D)

D: [[ 5 -6]
 [-2  5]
 [ 4  2]]


### Transpose D to create E

In [5]:
E= D.T
print("E:", E)

E: [[ 5 -2  4]
 [-6  5  2]]


### What does `shape` return?

In [6]:
arr = E.shape
m, n= E.shape
print(arr)
print("m:", m)
print("n:", n)

(2, 3)
m: 2
n: 3


### Generating values using `arange` and `linspace`

In [7]:
print(np.pi)
EqualSpaced = np.arange(0, 2 * np.pi, np.pi / 10)
EqualSpaced1 = np.linspace(0, 2 * np.pi, 21)
print("EqualSpaced:", EqualSpaced)
print("EqualSpaced1:", EqualSpaced1)

3.141592653589793
EqualSpaced: [0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265 3.45575192
 3.76991118 4.08407045 4.39822972 4.71238898 5.02654825 5.34070751
 5.65486678 5.96902604]
EqualSpaced1: [0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265 3.45575192
 3.76991118 4.08407045 4.39822972 4.71238898 5.02654825 5.34070751
 5.65486678 5.96902604 6.28318531]


### Find the maximum and minimum in each column of A

In [8]:
print(A)
maxcolA = np.max(A, axis=0)
mincolA = np.min(A, axis=0)
print("maxcolA:", maxcolA)
print("mincolA:", mincolA)

[[  1   2 -10   4]
 [  3   4   5  -6]
 [  3   3  -2   5]]
maxcolA: [3 4 5 5]
mincolA: [  1   2 -10  -6]


### Find the maximum and minimum in each row of A

In [9]:
print(A)
maxrowA = np.max(A, axis=1)
minrowA = np.min(A, axis=1)
print("maxrowA:", maxrowA)
print("minrowA:", minrowA)

[[  1   2 -10   4]
 [  3   4   5  -6]
 [  3   3  -2   5]]
maxrowA: [4 5 5]
minrowA: [-10  -6  -2]


### Find the maximum and minimum elements in the entire matrix A

In [10]:
maxA = np.max(A)
minA = np.min(A)
print("maxA:", maxA)
print("minA:", minA)

maxA: 5
minA: -10


### Calculate mean and sum of all elements in A

In [11]:
meanA = np.mean(A)
sumA = np.sum(A)
print(A)
print("meanA:", meanA)
print("sumA:", sumA)


[[  1   2 -10   4]
 [  3   4   5  -6]
 [  3   3  -2   5]]
meanA: 1.0
sumA: 12


### Create matrices F and G with random integers from -4 to 4

In [12]:
F = np.random.randint(-4, 5, (5, 3))
G = np.random.randint(-4, 5, (5, 3))
print("F:", F)
print("G:", G)

F: [[ 3 -1 -3]
 [-2  4  2]
 [ 2  0  0]
 [ 1 -2 -4]
 [-2  3  4]]
G: [[ 2  1 -4]
 [ 4  3 -3]
 [ 3  1  4]
 [-4  2 -2]
 [ 1 -2  4]]


#### Perform scalar multiplication, addition, subtraction, and element-wise multiplication on F and G

In [13]:
ScMultF = 0.4 * F
SumFG = F + G
DiffFG = F - G
ElProdFG = F * G
print("ScMultF:", ScMultF)
print("SumFG:", SumFG)
print("DiffFG:", DiffFG)
print("ElProdFG:", ElProdFG)

sizeF = F.shape
sizeA = A.shape


ScMultF: [[ 1.2 -0.4 -1.2]
 [-0.8  1.6  0.8]
 [ 0.8  0.   0. ]
 [ 0.4 -0.8 -1.6]
 [-0.8  1.2  1.6]]
SumFG: [[ 5  0 -7]
 [ 2  7 -1]
 [ 5  1  4]
 [-3  0 -6]
 [-1  1  8]]
DiffFG: [[ 1 -2  1]
 [-6  1  5]
 [-1 -1 -4]
 [ 5 -4 -2]
 [-3  5  0]]
ElProdFG: [[ 6 -1 12]
 [-8 12 -6]
 [ 6  0  0]
 [-4 -4  8]
 [-2 -6 16]]


### How do we go about Multiplying Matrices?

In [14]:
if sizeF[1] == sizeA[0]:
    H = F @ A
    print("H:", H)
else:
    print("Cannot multiply F and A due to incompatible dimensions.")

H: [[ -9  -7 -29   3]
 [ 16  18  36 -22]
 [  2   4 -20   8]
 [-17 -18 -12  -4]
 [ 19  20  27  -6]]


### Generate the identity matrix with 3 rows and 3 columns

In [15]:
eye33 = np.eye(4)
print(eye33)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Generate matrices of zeros with size 5x3 and ones with size 4x2

In [16]:
zeros53 = np.zeros((4, 3))
ones42 = np.ones((5, 2))
print("zeros53:", zeros53)
print("ones42:", ones42)

zeros53: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones42: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### Generate a diagonal matrix S with the diagonal elements 1, 2, 7

In [17]:
S = np.diag([1, 2, 7, 5])
print("S:", S)

S: [[1 0 0 0]
 [0 2 0 0]
 [0 0 7 0]
 [0 0 0 5]]


### Extract the diagonal elements from a random 6x6 matrix

In [18]:
R = np.random.randint(-6, 6, (6, 6))
diagR = np.diag(R)
print("R:", R)
print("diagR:", diagR)

R: [[-6 -6  0  3 -2 -6]
 [ 2  3  5  5  3  3]
 [-1 -6  0 -3  2  2]
 [-3  2 -4  5 -6  0]
 [ 3  3 -2  2  0  5]
 [ 2  4  0 -3 -1  1]]
diagR: [-6  3  0  5  0  1]
