In [1]:
import numpy as np

def create_magic_like(n):
    magic_square = np.zeros((n, n), dtype=int)
    row, col = 0, n // 2
    num = 1
    while num <= n*n:
        magic_square[row, col] = num
        num += 1
        new_row, new_col = (row - 1) % n, (col + 1) % n
        if magic_square[new_row, new_col]:
            row += 1
        else:
            row, col = new_row, new_col
    return magic_square


A = create_magic_like(5)


b = np.array([10, 26, 42, 59, 38])

# Print matrix A and vector b
print("Matrix A:")
print(A)
print("\nVector b:", b)

Matrix A:
[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]

Vector b: [10 26 42 59 38]


In [2]:
x = np.linalg.solve(A, b)

print("\nSolution vector x:")
print(x)



Solution vector x:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]


In [3]:
r = np.dot(A, x) - b

print("\nResidual vector r:")
print(r)


Residual vector r:
[ 0.00000000e+00  3.55271368e-15  0.00000000e+00  0.00000000e+00
 -7.10542736e-15]


In [4]:
import scipy.linalg
P, L, U = scipy.linalg.lu(A)


x1 = np.linalg.solve(A, b)


err1 = np.dot(A, x1) - b

print("Matrix P (Permutation matrix):")
print(P)
print("\nMatrix L (Lower triangular matrix):")
print(L)
print("\nMatrix U (Upper triangular matrix):")
print(U)
print("\nSolution vector x1:")
print(x1)
print("\nError vector err1:")
print(err1)

print(np.dot(L,U))

Matrix P (Permutation matrix):
[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

Matrix L (Lower triangular matrix):
[[1.         0.         0.         0.         0.        ]
 [0.73913043 1.         0.         0.         0.        ]
 [0.47826087 0.76873662 1.         0.         0.        ]
 [0.17391304 0.25267666 0.5163652  1.         0.        ]
 [0.43478261 0.48394004 0.72308355 0.92307692 1.        ]]

Matrix U (Upper triangular matrix):
[[ 23.           5.           7.          14.          16.        ]
 [  0.          20.30434783  -4.17391304  -2.34782609   3.17391304]
 [  0.           0.          24.8608137   -2.89079229  -1.09207709]
 [  0.           0.           0.          19.65116279  18.97932817]
 [  0.           0.           0.           0.         -22.22222222]]

Solution vector x1:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Error vector err1:
[ 0.00000000e+00  3.55271368e-15  0.00000000e+00  0.00000000e+00
 -7.

In [5]:
y = np.linalg.lstsq(A, b, rcond=None)[0]

print("\nSolution vector y:")
print(y)


Solution vector y:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]


In [6]:
# Solve the system Ax = b using matrix inverse
A_inv = np.linalg.inv(A)
x2 = np.dot(A_inv, b)

# Calculate the residual r2 and error err2
r2 = np.dot(A, x2) - b
err2 = x - x2

# Print solution vector x2, residual r2 and error err2
print("\nSolution vector x2 using inverse:")
print(x2)
print("\nResidual vector r2:")
print(r2)
print("\nError vector err2:")
print(err2)


Solution vector x2 using inverse:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Residual vector r2:
[-3.55271368e-15 -3.55271368e-15 -7.10542736e-15  0.00000000e+00
 -7.10542736e-15]

Error vector err2:
[-7.63278329e-17  4.16333634e-17  0.00000000e+00  4.44089210e-16
  5.55111512e-17]


In [7]:
def rref(A):


    A = A.astype(float)

    # Get matrix dimensions
    m, n = A.shape  # m: number of rows, n: number of columns

    # Track the leading column (pivot column) we're currently processing
    lead = 0

    # Iterate through each row of the matrix
    for r in range(m):
        # Stop if we've processed all columns
        if lead >= n:
            break

        # Handle zero pivot: find a non-zero row to swap
        if A[r, lead] == 0:
            # Search for a non-zero element in the same column in rows below
            for i in range(r + 1, m):
                if A[i, lead] != 0:
                    # Swap rows to bring a non-zero element to the current row
                    A[[r, i]] = A[[i, r]]
                    break

        # Process the row if we have a non-zero pivot
        if A[r, lead] != 0:
            # Step 1: Normalize the row by dividing by the pivot
            # This creates a leading 1 in the pivot column
            A[r] = A[r] / A[r, lead]

            # Step 2: Eliminate the pivot column in all other rows
            for i in range(m):
                if i != r:
                    # Subtract multiples to zero out the column
                    # in all rows except the current row
                    A[i] -= A[i, lead] * A[r]

        # Move to the next column
        lead += 1

    return A

In [8]:
C = np.hstack((A, b[:, np.newaxis]))
print(C)
R = rref(C)
print(R)

# Extract solution vector x3 from the RREF matrix
x3 = R[:, -1]

# Calculate residuals
r3 = np.dot(A, x3) - b
err3 = x - x3

print("\nSolution vector x3 (from RREF):")
print(x3)
print("\nResidual vector r3 (from RREF):")
print(r3)
print("\nError vector err3 (difference between x and x3):")
print(err3)

[[17 24  1  8 15 10]
 [23  5  7 14 16 26]
 [ 4  6 13 20 22 42]
 [10 12 19 21  3 59]
 [11 18 25  2  9 38]]
[[ 1.          0.          0.          0.          0.         -0.00833333]
 [ 0.          1.          0.          0.          0.          0.0724359 ]
 [ 0.          0.          1.          0.          0.          1.47179487]
 [-0.         -0.         -0.          1.          0.          1.48782051]
 [ 0.          0.          0.          0.          1.         -0.33141026]]

Solution vector x3 (from RREF):
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Residual vector r3 (from RREF):
[1.77635684e-15 7.10542736e-15 0.00000000e+00 2.13162821e-14
 0.00000000e+00]

Error vector err3 (difference between x and x3):
[-2.67147415e-16  9.71445147e-17  0.00000000e+00 -4.44089210e-16
  2.22044605e-16]


In [9]:
import time

# Initialize Num
Num = 500

# Generate matrix A and vector b
A = np.random.rand(Num, Num) + Num * np.eye(Num)
b = np.random.rand(Num, 1)

# Method 1: Solve using backslash operator
start_time = time.time()
x1 = np.linalg.solve(A, b)
end_time = time.time()
time_backslash = end_time - start_time

# Method 2: Solve using matrix inverse
start_time = time.time()
x2 = np.linalg.inv(A) @ b
end_time = time.time()
time_inv = end_time - start_time

# Method 3: Solve using reduced row echelon form (rref)
start_time = time.time()
C = np.hstack((A, b))
R = rref(C)
x3 = R[:, -1]
end_time = time.time()
time_rref = end_time - start_time

# Print the solution vectors and computational times
print("\nSolution vector x1 (using backslash operator):")
print(x1)
print("\nSolution vector x2 (using matrix inverse):")
print(x2)
print("\nSolution vector x3 (using reduced row echelon form):")
print(x3)
print("\nComputational times:")
print(f"Backslash operator: {time_backslash} seconds")
print(f"Matrix inverse: {time_inv} seconds")
print(f"Reduced row echelon form (rref): {time_rref} seconds")


Solution vector x1 (using backslash operator):
[[ 1.61013639e-03]
 [ 1.44212894e-04]
 [ 1.10981877e-03]
 [ 4.46966487e-04]
 [ 3.56646233e-04]
 [-7.76228213e-06]
 [ 6.20447803e-04]
 [-2.12917413e-04]
 [ 1.24584318e-03]
 [ 2.77629672e-04]
 [ 1.12568900e-03]
 [-2.36149914e-04]
 [ 3.87706410e-04]
 [ 4.14506659e-04]
 [-2.59821260e-04]
 [ 1.21180331e-03]
 [ 2.57139025e-04]
 [ 9.00872447e-04]
 [-2.47821585e-04]
 [ 1.85181224e-04]
 [ 1.24620324e-03]
 [ 4.70096434e-04]
 [ 1.58710903e-03]
 [ 1.34558398e-03]
 [ 1.59313336e-04]
 [ 1.21131734e-03]
 [ 1.42784527e-03]
 [ 5.06941564e-04]
 [ 1.36589980e-03]
 [ 2.09081918e-04]
 [ 1.08772289e-03]
 [-5.87130105e-05]
 [ 7.89520877e-04]
 [-4.33051999e-05]
 [-7.87038944e-05]
 [ 1.82475517e-04]
 [ 3.46334243e-05]
 [ 1.22821642e-03]
 [ 3.47145744e-04]
 [ 3.15157627e-05]
 [ 8.82623135e-04]
 [ 1.95460625e-04]
 [ 1.46348470e-03]
 [ 1.19527449e-03]
 [ 4.17421719e-04]
 [ 1.01736893e-03]
 [ 2.71853491e-04]
 [ 4.34063830e-04]
 [ 9.54011294e-04]
 [ 5.44080922e-04]
 [

In [10]:
# Define matrix A and vector b for the overdetermined system
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10],
              [9, 11, 12]])
b = np.array([1, 2, 3, 4]).reshape(-1, 1)

# Solve the system Ax = b using the backslash operator
x = np.linalg.lstsq(A, b, rcond=None)[0]

# Calculate the residual r = Ax - b
r = np.dot(A, x) - b

# Print the solution vector x
print("\nSolution vector x:")
print(x)

# Print the residual vector r
print("\nResidual vector r:")
print(r)

# Calculate and print the solution using normal equations for comparison
ATA_inv = np.linalg.inv(np.dot(A.T, A))  # Calculate (A.T * A)^(-1)
ATb = np.dot(A.T, b)  # Calculate A.T * b
y = np.dot(ATA_inv, ATb)  # Solve normal equations A.T * A * y = A.T * b

# Calculate the difference between x and y to verify accuracy
err = x - y

# Print the solution vector y from normal equations
print("\nSolution vector y (from normal equations):")
print(y)

# Print the difference vector err (should be close to zero)
print("\nDifference vector err (x - y):")
print(err)


Solution vector x:
[[-0.24630542]
 [ 0.38916256]
 [ 0.16256158]]

Residual vector r:
[[ 0.01970443]
 [-0.06403941]
 [ 0.01477833]
 [ 0.01477833]]

Solution vector y (from normal equations):
[[-0.24630542]
 [ 0.38916256]
 [ 0.16256158]]

Difference vector err (x - y):
[[-1.13797860e-15]
 [-3.75255382e-14]
 [ 1.19071419e-14]]
